# Generated by Django 3.2.8 on 2021-10-19 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('end_body', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('D', 'Document'), ('A', 'Announcement')], default='D', max_length=1)),
            ],
            options={
                'ordering': ['name', 'doc_type'],
            },
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcaf_id', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=13)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='api.soldier')),
            ],
        ),
        migrations.CreateModel(
            name='Subdepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.soldier')),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_soldier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.soldier')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soldier'),
        ),
        migrations.AddField(
            model_name='department',
            name='soldier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.soldier'),
        ),
        migrations.AddField(
            model_name='department',
            name='subdepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subdepartment'),
        ),
    ]
