# Generated by Django 3.2.8 on 2021-10-18 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcaf_id', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('end_body', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('D', 'Document'), ('A', 'Announcement')], default='D', max_length=1)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soldier')),
            ],
            options={
                'ordering': ['name', 'doc_type'],
            },
        ),
    ]
