# Generated by Django 3.2.8 on 2021-10-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='destination_soldier',
            field=models.IntegerField(),
        ),
    ]
