# Generated by Django 3.2.8 on 2021-10-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_soldier_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='soldier',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.soldier')),
            ],
        ),
        migrations.CreateModel(
            name='Subdepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.soldier')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='soldier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.soldier'),
        ),
        migrations.AddField(
            model_name='department',
            name='subdepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subdepartment'),
        ),
    ]
